### ISSUE TITLE
[Feature Request] Selectable Soundpack

### ISSUE THREAD

**Issue by rootEnginear** [shuhaoli/hikaru-gotham-move#1]
Hello! In the latest Hikaru stream, he did mention how can we expand this extension with a sound pack. I was thinking that we can replace the dropdown with checkboxes to select sound packs of chess players we like, so more sounds can be added in the future. I also could work on this feature if you want.

(Also, Levy was saying more voice lines in his stream which we can also add them later.)

**Comment by shuhaoli** [comment]
Yes, replacing the dropdown with multi-select checkboxes would be great for future extendability. It wasn't originally an option because of Levy only having ~5 lines, which would get repetitive really quickly if someone were to only select Levy. However, the extra lines Levy provided on stream should help with that problem.

Feel free to work on this feature!
